version: "3.9"
networks:
  myapp-network:
services:
  web:
    build: .
    restart: "unless-stopped"
    networks:
      - myapp-network
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      FLASK_ENV: development
  redis:
    image: "redis:alpine"
    restart: "unless-stopped"
    networks:
      - myapp-network
    expose:
      - "6379"
